import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./(components)/Header";
import Footer from "./(components)/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {/* <BetaMessage /> */}
        {children}
        <hr
          style={{
            border: "none",
            borderTop: "1px solid #e0e0e0",
            margin: 0,
            padding: 0,
          }}
        />

        <Footer />
      </body>
    </html>
  );
}
